# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/work/FPGA/TDMA-picozed/vanet-tdma2017/axi_tdma_ath9k_middleware_project/src/cmd_fifo/cmd_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cmd_fifo || ORIG_REF_NAME==cmd_fifo}]

# XDC: e:/work/FPGA/TDMA-picozed/vanet-tdma2017/axi_tdma_ath9k_middleware_project/src/cmd_fifo/cmd_fifo/cmd_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmd_fifo || ORIG_REF_NAME==cmd_fifo}] {/U0 }]/U0 ]]
